### ISSUE TITLE
State Management vs Branch Programming

### ISSUE THREAD

**Issue by namper** [lashax/CarWash#2]
https://github.com/lashax/CarWash/blob/0ee0a281dcae293e8036bd377509679ff3fe8f06/washing_service/view_helpers/washers.py#L8

ჯობია აქ სტეიტ მენეჯმენტი გააკეთო დიქშენარის დახმარებით აგისწრაფებს კოდს

**Comment by lashax** [comment]
64b514bc4f825fc875baa9231a8e401db9e6b0fa
